name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BSG1_MAYHEMFILE: Mayhem/fuzz_blst_serde_g1.mayhemfile
  BSG2_MAYHEMFILE: Mayhem/fuzz_blst_serde_g2.mayhemfile
  DAG1_MAYHEMFILE: Mayhem/fuzz_differential_add_g1.mayhemfile
  DAG2_MAYHEMFILE: Mayhem/fuzz_differential_add_g2.mayhemfile
  DMG1_MAYHEMFILE: Mayhem/fuzz_differential_mul_g1.mayhemfile
  DMG2_MAYHEMFILE: Mayhem/fuzz_differential_mul_g2.mayhemfile
  DSG1_MAYHEMFILE: Mayhem/fuzz_differential_serde_g1.mayhemfile
  DSG2_MAYHEMFILE: Mayhem/fuzz_differential_serde_g2.mayhemfile
  MSG1_MAYHEMFILE: Mayhem/fuzz_milagro_serde_g1.mayhemfile
  MSG2_MAYHEMFILE: Mayhem/fuzz_milagro_serde_g2.mayhemfile

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile_mayhem

      - name: Start analysis for BSG1
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.BSG1_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for BSG2
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.BSG2_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DAG1
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DAG1_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DAG2
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DAG2_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DMG1
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DMG1_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DMG2
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DMG2_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DSG1
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DSG1_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for DSG2
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DSG2_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for MSG1
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.MSG1_MAYHEMFILE }}
          sarif-output: sarif

      - name: Start analysis for MSG2
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.MSG2_MAYHEMFILE }}
          sarif-output: sarif

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif
